version: '2'
services:
  api:
    build: .
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
    ports:
      - 3000:${PORT}
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}