name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag chat-app-api
      
    - name: Push the Docker image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
      run: docker push $DOCKER_USER/chat-app-api
